# Generated by Django 5.1.2 on 2025-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Номер позиции в топе (1, 2, 3...)', unique=True, verbose_name='Позиция в рейтинге')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 300x300px', upload_to='image/', verbose_name='Изображение игры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['rank'],
            },
        ),
    ]
