# Generated by Django 5.1.2 on 2025-06-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для картинки'),
        ),
    ]
