# Generated by Django 5.1.2 on 2025-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицировано в Telegram'),
        ),
    ]
