# Generated by Django 5.1.2 on 2025-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram логин')),
                ('address', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Адрес кошелька')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя в Telegram')),
                ('telegram_last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия в Telegram')),
                ('telegram_photo_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='Аватар Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
                'ordering': ['-created_at'],
            },
        ),
    ]
