# Generated by Django 5.1.2 on 2025-06-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users_images/baseavatar.jpg', null=True, upload_to='users_images', verbose_name='Аватар'),
        ),
    ]
