# Generated by Django 5.1.2 on 2024-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='slides/backgrounds/')),
                ('animal_name', models.CharField(max_length=200)),
                ('animal_image', models.ImageField(upload_to='slides/animals/')),
                ('caption', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('video', models.FileField(upload_to='slides/videos/')),
                ('video_description', models.TextField()),
            ],
        ),
    ]
