# Generated by Django 5.1.2 on 2024-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'слайды и описание', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='slide',
            name='paragraph_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка в параграфе'),
        ),
        migrations.AddField(
            model_name='slide',
            name='video_description_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка параграфа модального окна'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='animal_image',
            field=models.ImageField(upload_to='slides/animals/', verbose_name='Маленькая картинка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='animal_name',
            field=models.CharField(max_length=200, verbose_name='Главные большые буквы'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='bg_image',
            field=models.ImageField(upload_to='slides/backgrounds/', verbose_name='Главная картинка backround'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='Текст над большими буквами'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='paragraph',
            field=models.TextField(verbose_name='Текст главной страницы параграф 1'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video_description',
            field=models.TextField(verbose_name='Текст модального окна видео'),
        ),
    ]
