# Generated by Django 5.1.2 on 2025-01-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Приветствие')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка героя')),
            ],
            options={
                'verbose_name': 'Картинку героя и приветствие',
                'verbose_name_plural': 'Картинки героев и приветствие',
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка')),
                ('content_1', models.TextField(verbose_name='Текст 1')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение 1')),
                ('content_2', models.TextField(verbose_name='Текст 2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение 2')),
                ('content_3', models.TextField(verbose_name='Текст 3')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(default=0, verbose_name='Время чтения')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('reading_time', models.CharField(default='3 mins read', max_length=20, verbose_name='Время чтения')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author_images/', verbose_name='Изображение автора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='blog.post')),
            ],
            options={
                'verbose_name': 'в избранные',
                'verbose_name_plural': 'Избранные',
                'db_table': 'featured',
            },
        ),
        migrations.CreateModel(
            name='RecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Значок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(default=0, verbose_name='Время чтения')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('tags', models.ManyToManyField(related_name='recentpost', to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'в recent post',
                'verbose_name_plural': 'Recent Post',
                'db_table': 'posts Recent Post',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post', to='blog.tag', verbose_name='Теги'),
        ),
    ]
