# Generated by Django 5.1.2 on 2025-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='Изображение тега'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='author_name',
            field=models.CharField(default='admin', max_length=100, verbose_name='Имя автора'),
        ),
    ]
