# Generated by Django 5.1.2 on 2024-11-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка героя')),
            ],
            options={
                'verbose_name': 'Картинка героя',
                'verbose_name_plural': 'Картинки героев',
                'db_table': 'hero',
            },
        ),
    ]
