# Generated by Django 5.1.2 on 2024-11-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Картинку героя', 'verbose_name_plural': 'Картинки героев'},
        ),
    ]
