# Generated by Django 5.1.2 on 2024-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_hero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('reading_time', models.CharField(default='3 mins read', max_length=20, verbose_name='Время чтения')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author_images/', verbose_name='Изображение автора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'в избранные',
                'verbose_name_plural': 'Избранные',
                'db_table': 'featured',
            },
        ),
    ]
