# Generated by Django 5.1.2 on 2025-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_popularity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность поста'),
        ),
        migrations.AddField(
            model_name='recentpost',
            name='popularity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность поста'),
        ),
    ]
