# Generated by Django 5.1.2 on 2025-01-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recent_post',
        ),
        migrations.CreateModel(
            name='CommentRecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=50)),
                ('text', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.recentpost')),
            ],
        ),
    ]
