# Generated by Django 5.1.2 on 2025-02-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_options_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
