# Generated by Django 5.1.2 on 2025-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
