# Generated by Django 5.1.2 on 2025-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentpost',
            options={'verbose_name': 'в recent post', 'verbose_name_plural': 'Recent Post Game'},
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AlterField(
            model_name='recentpost',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для кнопки'),
        ),
    ]
