# Generated by Django 5.1.2 on 2025-02-21 13:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_recentpost_options_alter_post_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
