# Generated by Django 5.1.2 on 2025-02-21 14:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_recentpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_2',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_3',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
