# Generated by Django 5.1.2 on 2025-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_hero_content_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка'),
        ),
    ]
