# Generated by Django 5.1.2 on 2025-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_recentpost_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='recentpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (SEO)'),
        ),
    ]
