# Generated by Django 5.1.2 on 2025-07-23 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_meta_description_recentpost_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='is_video',
            field=models.BooleanField(default=False, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Это видео?'),
        ),
        migrations.AddField(
            model_name='recentpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Видео файл'),
        ),
    ]
