# Generated by Django 5.1.2 on 2025-07-23 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_recentpost_is_video_recentpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentpost',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='recentpost',
            name='video',
        ),
        migrations.AddField(
            model_name='featured',
            name='is_video',
            field=models.BooleanField(default=False, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Это видео?'),
        ),
        migrations.AddField(
            model_name='featured',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Видео файл'),
        ),
    ]
