# Generated by Django 5.1.2 on 2025-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_recentpost_is_video_remove_recentpost_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
    ]
