# Generated by Django 5.1.2 on 2025-07-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_featured_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Это видео?'),
        ),
    ]
