"""
Django settings for appshopmaster project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загрузка переменных окружения из .env

from django.conf.global_settings import AUTH_USER_MODEL, CACHES, MEDIA_ROOT, MEDIA_URL

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-i3qyxd*5w*etynbov!o%q=uay)ck2zg2bw&i6&@@a-q8-tg0+#'

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

DEBUG = False

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = [
								'gameton.app',
								'www.gameton.app',
								'80.64.24.110',
								'127.0.0.1',
								'ai-neuro-box.ru',
								]

SITE_ID = 1
# 'django.contrib.sites',

# Application definition

INSTALLED_APPS = [
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'django.contrib.postgres',
		'django_ckeditor_5',

		'django.contrib.sites',
		

		'main',
		'goods',
		'blog',
		'users',
]

		# 'debug_toolbar',


MIDDLEWARE = [
		'django.middleware.security.SecurityMiddleware',
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

		# "debug_toolbar.middleware.DebugToolbarMiddleware",



ROOT_URLCONF = 'app_shopmaster.urls'

TEMPLATES = [
		{
				'BACKEND': 'django.template.backends.django.DjangoTemplates',
				'DIRS': [BASE_DIR / 'templates'],
				'APP_DIRS': True,
				'OPTIONS': {
						'context_processors': [
								'django.template.context_processors.debug',
								'django.template.context_processors.request',
								'django.template.context_processors.tz',
								'django.contrib.auth.context_processors.auth',
								'django.contrib.messages.context_processors.messages',
								'blog.context_processors.latest_comments',
						],
				},
		},
]

WSGI_APPLICATION = 'app_shopmaster.wsgi.application'


CKEDITOR_5_CONFIGS = {
		'default': {
				'toolbar': ['heading', '|', 'bold', 'italic', 'underline', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo'],
				'language': 'ru',
				'htmlSupport': {
						'allow': [
								{'name': '/.*/', 'attributes': True, 'classes': True, 'styles': True}
						]
				},
				'htmlEmbed': {
						'showPreviews': True
				},
				'link': {
						'decorators': {
								'openInNewTab': {
										'mode': 'manual',
										'label': 'Open in a new tab',
										'attributes': {
												'target': '_blank',
												'rel': 'noopener noreferrer'
										}
								}
						}
				},
		}
}

# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
# 		'default': {
# 				'ENGINE': 'django.db.backends.sqlite3',
# 				'NAME': BASE_DIR / 'db.sqlite3',
# 		}
# }


# DATABASES = {
# 		'default': {
# 				'ENGINE': 'django.db.backends.postgresql',
# 				'NAME': 'TonGameApp',
# 				'USER': 'admin',
# 				'PASSWORD': 'admin',
# 				'HOST': 'localhost',
# 				'PORT': '5432',
# 		}
# }


DATABASES = {
		'default': {
				'ENGINE': 'django.db.backends.postgresql',
				'NAME': 'TonGameApp',
				'USER': 'admin',
				'PASSWORD': 'admin',
				'HOST': '80.64.24.110',
				'PORT': '5432',
		}
}

CACHES = {
		"default": {
				"BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
				"LOCATION": BASE_DIR / "cache",
		}
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
		{
				'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
		},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# меняем язык админки на русский язык
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Папка для сбора статических файлов

STATICFILES_DIRS = [
	BASE_DIR / 'static'
	]

MEDIA_URL = '/media/' # URL-префикс для медиафайлов

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

####################

# MEDIA_ROOT = BASE_DIR / 'media' # Папка для хранения медиафайлов

####################

INTERNAL_IPS = [
		# ...
		"127.0.0.1",
		# ...
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'


TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 МБ
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 МБ

