# Generated by Django 5.1.2 on 2025-01-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_productsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
